name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image - x86
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: eduardogobetti/blog:x86-latest, eduardogobetti/blog:x86-v${{ github.run_number }}
          file: docker/x86/Dockerfile 

      - name: Build and Push Docker Image - ARM
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: eduardogobetti/blog:arm-latest, eduardogobetti/blog:arm-v${{ github.run_number }}
          platforms: linux/arm/v7
          file: docker/arm/Dockerfile 

# jobs:
#   ci:
#     name: Build Container
#     runs-on: ubuntu-latest  
#     strategy:
#         matrix:
#           platform: [x86, arm]

#     steps:          
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USER }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build and Push to Docker Hub
#         uses: docker/build-push-action@v3
#         with:
#           context: .
#           push: true
#           tags: eduardogobetti/blog:${{ matrix.platform }}-latest, eduardogobetti/blog:${{ matrix.platform }}-v${{ github.run_number }}
#           file: docker/${{ matrix.platform }}/Dockerfile  