name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  ci:
      name: Build Container
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: eduardogobetti/blog:latest, eduardogobetti/blog:v${{github.run_number}}       